import '../models/user.dart';
import '../models/post.dart';
import '../models/community.dart';
import '../models/notification.dart';
import '../models/comment.dart';

/// Generador de datos - vacío para usar solo datos del backend
class MockData {
  
  // Usuarios - vacío, usar backend
  static List<User> getUsers() {
    return [];
  }

  // Comunidades - vacío, usar backend
  static List<Community> getCommunities() {
    return [];
  }

  // Posts - vacío, usar backend
  static List<Post> getPosts() {
    return [];
  }

  // Comentarios - vacío, usar backend
  static List<Comment> getComments() {
    return [];
  }

  // Notificaciones - vacío, usar backend
  static List<NotificationModel> getNotifications() {
    return [];
  }
}

        id: 1,
        nombre: 'Juan Pérez',
        email: 'juan.perez@utp.edu.pe',
        biografia: 'Estudiante de Ingeniería de Sistemas. Apasionado por la programación y el desarrollo web.',
        fotoPerfil: 'https://i.pravatar.cc/150?u=1',
        postsCount: 23,
        comunidadesCount: 5,
        fechaCreacion: DateTime.now().subtract(const Duration(days: 365)),
      ),
      User(
        id: 2,
        nombre: 'María García',
        email: 'maria.garcia@utp.edu.pe',
        biografia: 'Estudiante de Medicina. Amante de la fotografía y los viajes.',
        fotoPerfil: 'https://i.pravatar.cc/150?u=2',
        postsCount: 45,
        comunidadesCount: 8,
        fechaCreacion: DateTime.now().subtract(const Duration(days: 400)),
      ),
      User(
        id: 3,
        nombre: 'Carlos Rodríguez',
        email: 'carlos.rodriguez@utp.edu.pe',
        biografia: 'Estudiante de Arquitectura. Diseñador y creador de contenido.',
        fotoPerfil: 'https://i.pravatar.cc/150?u=3',
        postsCount: 12,
        comunidadesCount: 3,
        fechaCreacion: DateTime.now().subtract(const Duration(days: 200)),
      ),
      User(
        id: 4,
        nombre: 'Ana Martínez',
        email: 'ana.martinez@utp.edu.pe',
        biografia: 'Estudiante de Derecho. Debate y oratoria.',
        fotoPerfil: 'https://i.pravatar.cc/150?u=4',
        postsCount: 89,
        comunidadesCount: 12,
        fechaCreacion: DateTime.now().subtract(const Duration(days: 600)),
      ),
      User(
        id: 5,
        nombre: 'Pedro Sánchez',
        email: 'pedro.sanchez@utp.edu.pe',
        biografia: 'Estudiante de Psicología. Interesado en la salud mental estudiantil.',
        fotoPerfil: 'https://i.pravatar.cc/150?u=5',
        postsCount: 34,
        comunidadesCount: 6,
        fechaCreacion: DateTime.now().subtract(const Duration(days: 300)),
      ),
      User(
        id: 6,
        nombre: 'Laura Torres',
        email: 'laura.torres@utp.edu.pe',
        biografia: 'Estudiante de Administración. Emprendedora y líder estudiantil.',
        fotoPerfil: 'https://i.pravatar.cc/150?u=6',
        postsCount: 56,
        comunidadesCount: 7,
        fechaCreacion: DateTime.now().subtract(const Duration(days: 450)),
      ),
    ];
  }

  // Comunidades de prueba
  static List<Community> getCommunities() {
    return [
      Community(
        id: 1,
        nombre: 'Desarrollo Web UTP',
        descripcion: 'Comunidad para estudiantes interesados en desarrollo web, frontend, backend y tecnologías modernas. Compartimos recursos, proyectos y oportunidades.',
        imagen: 'https://picsum.photos/seed/web/400/300',
        miembros: 234,
        posts: 456,
        esMiembro: false,
        creador: 'Juan Pérez',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 180)),
      ),
      Community(
        id: 2,
        nombre: 'Medicina UTP - Grupo de Estudio',
        descripcion: 'Espacio de colaboración para estudiantes de medicina. Compartimos apuntes, casos clínicos y material de estudio.',
        imagen: 'https://picsum.photos/seed/medicina/400/300',
        miembros: 567,
        posts: 1234,
        esMiembro: true,
        creador: 'María García',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 365)),
      ),
      Community(
        id: 3,
        nombre: 'Fotografía UTP',
        descripcion: 'Comunidad de fotógrafos aficionados y profesionales. Compartimos fotos, técnicas y organizamos salidas fotográficas.',
        imagen: 'https://picsum.photos/seed/foto/400/300',
        miembros: 178,
        posts: 890,
        esMiembro: false,
        creador: 'María García',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 120)),
      ),
      Community(
        id: 4,
        nombre: 'Club de Programación Competitiva',
        descripcion: 'Preparación para concursos de programación ICPC. Algoritmos, estructuras de datos y resolución de problemas.',
        imagen: 'https://picsum.photos/seed/cp/400/300',
        miembros: 89,
        posts: 234,
        esMiembro: true,
        creador: 'Juan Pérez',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 90)),
      ),
      Community(
        id: 5,
        nombre: 'Emprendedores UTP',
        descripcion: 'Red de emprendedores universitarios. Networking, mentorías y oportunidades de negocio.',
        imagen: 'https://picsum.photos/seed/emprende/400/300',
        miembros: 445,
        posts: 678,
        esMiembro: false,
        creador: 'Laura Torres',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 240)),
      ),
      Community(
        id: 6,
        nombre: 'Deportes UTP',
        descripcion: 'Todo sobre deportes en la universidad. Fútbol, vóley, básquet y más. Organización de campeonatos.',
        imagen: 'https://picsum.photos/seed/deportes/400/300',
        miembros: 890,
        posts: 1567,
        esMiembro: true,
        creador: 'Pedro Sánchez',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 300)),
      ),
      Community(
        id: 7,
        nombre: 'Grupo de Investigación - AI',
        descripcion: 'Investigación en Inteligencia Artificial y Machine Learning. Paper discussions y proyectos de investigación.',
        imagen: 'https://picsum.photos/seed/ai/400/300',
        miembros: 67,
        posts: 123,
        esMiembro: false,
        creador: 'Carlos Rodríguez',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 60)),
      ),
      Community(
        id: 8,
        nombre: 'Música y Arte',
        descripcion: 'Comunidad para artistas y músicos. Compartimos creaciones, organizamos jam sessions.',
        imagen: 'https://picsum.photos/seed/musica/400/300',
        miembros: 234,
        posts: 567,
        esMiembro: false,
        creador: 'Ana Martínez',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 150)),
      ),
      Community(
        id: 9,
        nombre: 'Gaming UTP',
        descripcion: 'Comunidad de gamers. Torneos de Valorant, League of Legends, CS:GO y más. ¡Únete a las scrims!',
        imagen: 'https://picsum.photos/seed/gaming/400/300',
        miembros: 456,
        posts: 789,
        esMiembro: true,
        creador: 'Carlos Rodríguez',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 100)),
      ),
      Community(
        id: 10,
        nombre: 'Libros y Literatura',
        descripcion: 'Club de lectura universitario. Discusiones de libros, recomendaciones y intercambios.',
        imagen: 'https://picsum.photos/seed/libros/400/300',
        miembros: 123,
        posts: 345,
        esMiembro: false,
        creador: 'Pedro Sánchez',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 200)),
      ),
      Community(
        id: 11,
        nombre: 'Diseño UX/UI',
        descripcion: 'Comunidad de diseño de interfaces y experiencia de usuario. Tips, recursos y feedback.',
        imagen: 'https://picsum.photos/seed/design/400/300',
        miembros: 234,
        posts: 456,
        esMiembro: true,
        creador: 'Laura Torres',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 80)),
      ),
      Community(
        id: 12,
        nombre: 'Cine y Series',
        descripcion: 'Discusiones sobre películas, series, anime. Reviews y recomendaciones.',
        imagen: 'https://picsum.photos/seed/cine/400/300',
        miembros: 567,
        posts: 1234,
        esMiembro: false,
        creador: 'Ana Martínez',
        fechaCreacion: DateTime.now().subtract(const Duration(days: 180)),
      ),
    ];
  }

  // Publicaciones de prueba
  static List<Post> getPosts() {
    final now = DateTime.now();
    return [
      Post(
        id: 1,
        usuarioId: 1,
        comunidadId: 1,
        contenido: '🚀 Acabo de desplegar mi primera aplicación Flutter en la web! Estoy emocionado de compartir este proyecto con la comunidad. ¿Alguien más está trabajando con Flutter? #Flutter #WebDev',
        fecha: now.subtract(const Duration(hours: 2)),
        nombreUsuario: 'Juan Pérez',
        nombreComunidad: 'Desarrollo Web UTP',
        likes: 45,
        comentarios: 12,
      ),
      Post(
        id: 2,
        usuarioId: 2,
        comunidadId: 2,
        contenido: '📚 Resumen de clase de Cardiología: El corazón tiene 4 cámaras principales... Comparto mis apuntes para quienes necesiten repasar para el examen. ¡Éxitos a todos! 💪',
        fecha: now.subtract(const Duration(hours: 5)),
        nombreUsuario: 'María García',
        nombreComunidad: 'Medicina UTP - Grupo de Estudio',
        likes: 89,
        comentarios: 34,
      ),
      Post(
        id: 3,
        usuarioId: 3,
        comunidadId: 3,
        contenido: '📸 Fotografía del campus al atardecer. Me encanta cómo se ve la biblioteca con esa luz dorada. ¿Qué les parece?',
        fecha: now.subtract(const Duration(hours: 8)),
        nombreUsuario: 'Carlos Rodríguez',
        nombreComunidad: 'Fotografía UTP',
        likes: 234,
        comentarios: 67,
      ),
      Post(
        id: 4,
        usuarioId: 1,
        comunidadId: 4,
        contenido: '💡 Tip de algoritmos: Cuando trabajen con grafos, consideren usar BFS para encontrar el camino más corto en grafos no ponderados. Mucho más eficiente que DFS para este caso.',
        likes: 23,
        comentarios: 8,
        fecha: now.subtract(const Duration(hours: 12)),
        nombreUsuario: 'Juan Pérez',
        nombreComunidad: 'Club de Programación Competitiva',
      ),
      Post(
        id: 5,
        usuarioId: 6,
        comunidadId: 5,
        contenido: '🎯 Pitch perfecto: 5 minutos para convencer a un inversor. Mañana tenemos workshop de presentación de proyectos. ¡No falten! Lugar: Auditorio Central, 6pm.',
        likes: 156,
        comentarios: 45,
        fecha: now.subtract(const Duration(days: 1)),
        nombreUsuario: 'Laura Torres',
        nombreComunidad: 'Emprendedores UTP',
      ),
      Post(
        id: 6,
        usuarioId: 5,
        comunidadId: 6,
        contenido: '⚽ Resultados del campeonato interfacultades: Ingeniería 3 - 2 Medicina. Gran partido, felicitaciones a ambos equipos. 🏆',
        likes: 345,
        comentarios: 89,
        fecha: now.subtract(const Duration(days: 1, hours: 6)),
        nombreUsuario: 'Pedro Sánchez',
        nombreComunidad: 'Deportes UTP',
      ),
      Post(
        id: 7,
        usuarioId: 4,
        comunidadId: 8,
        contenido: '🎸 Nuevo cover en mi canal! Esta vez "Blackbird" de The Beatles. Link en bio. Espero sus comentarios!',
        likes: 78,
        comentarios: 23,
        fecha: now.subtract(const Duration(days: 2)),
        nombreUsuario: 'Ana Martínez',
        nombreComunidad: 'Música y Arte',
      ),
      Post(
        id: 8,
        usuarioId: 2,
        comunidadId: 3,
        contenido: '🌅 Golden hour en el campus. No me canso de esta vista.',
        likes: 456,
        comentarios: 123,
        fecha: now.subtract(const Duration(days: 2, hours: 8)),
        nombreUsuario: 'María García',
        nombreComunidad: 'Fotografía UTP',
      ),
      Post(
        id: 9,
        usuarioId: 1,
        comunidadId: 1,
        contenido: '❓ Pregunta a la comunidad: ¿React Native o Flutter para desarrollo móvil en 2024? Estoy planeando un nuevo proyecto y quiero sus opiniones basadas en experiencia real.',
        likes: 67,
        comentarios: 45,
        fecha: now.subtract(const Duration(days: 3)),
        nombreUsuario: 'Juan Pérez',
        nombreComunidad: 'Desarrollo Web UTP',
      ),
      Post(
        id: 10,
        usuarioId: 6,
        comunidadId: 5,
        contenido: '💰 Convocatoria abierta: Fondo de emprendimiento universitario. Postulaciones hasta el 30 de este mes. Requisitos: Proyecto viable, equipo comprometido, y ganas de crecer.',
        likes: 234,
        comentarios: 56,
        fecha: now.subtract(const Duration(days: 3, hours: 12)),
        nombreUsuario: 'Laura Torres',
        nombreComunidad: 'Emprendedores UTP',
      ),
      Post(
        id: 11,
        usuarioId: 3,
        comunidadId: 3,
        contenido: '🎨 Serie fotográfica: "Texturas de la UTP". Esta semana explorando los detalles arquitectónicos que normalmente pasamos por alto.',
        likes: 123,
        comentarios: 34,
        fecha: now.subtract(const Duration(days: 4)),
        nombreUsuario: 'Carlos Rodríguez',
        nombreComunidad: 'Fotografía UTP',
      ),
      Post(
        id: 12,
        usuarioId: 4,
        comunidadId: 2,
        contenido: '⚖️ Caso clínico interesante de la semana: Paciente con síntomas neurológicos atípicos. ¿Alguien quiere discutir el diagnóstico diferencial?',
        likes: 89,
        comentarios: 56,
        fecha: now.subtract(const Duration(days: 5)),
        nombreUsuario: 'Ana Martínez',
        nombreComunidad: 'Medicina UTP - Grupo de Estudio',
      ),
      Post(
        id: 13,
        usuarioId: 5,
        comunidadId: 6,
        contenido: '🏀 Convocatoria abierta para el equipo de básquet varones. Pruebas este sábado a las 3pm en el coliseo. ¡Vamos con todo!',
        likes: 234,
        comentarios: 45,
        fecha: now.subtract(const Duration(hours: 6)),
        nombreUsuario: 'Pedro Sánchez',
        nombreComunidad: 'Deportes UTP',
      ),
      Post(
        id: 14,
        usuarioId: 6,
        comunidadId: 5,
        contenido: '📊 Workshop: Como hacer un plan de negocios viable. Aprenderemos a calcular el TAM, SAM, SOM. Cupos limitados!',
        likes: 178,
        comentarios: 67,
        fecha: now.subtract(const Duration(hours: 8)),
        nombreUsuario: 'Laura Torres',
        nombreComunidad: 'Emprendedores UTP',
      ),
      Post(
        id: 15,
        usuarioId: 1,
        comunidadId: 7,
        contenido: '🤖 Paper review: "Attention is All You Need" - El paper que revolucionó el NLP. Mañana discutimos en la reunión semanal.',
        likes: 45,
        comentarios: 12,
        fecha: now.subtract(const Duration(hours: 4)),
        nombreUsuario: 'Juan Pérez',
        nombreComunidad: 'Grupo de Investigación - AI',
      ),
      Post(
        id: 16,
        usuarioId: 2,
        comunidadId: 3,
        contenido: '📷 Técnica de la semana: Regla de los tercios. Comparto un ejemplo aplicado en el campus. ¿Qué les parece la composición?',
        likes: 567,
        comentarios: 234,
        fecha: now.subtract(const Duration(hours: 2)),
        nombreUsuario: 'María García',
        nombreComunidad: 'Fotografía UTP',
      ),
      Post(
        id: 17,
        usuarioId: 3,
        comunidadId: 1,
        contenido: '💻 Hackathon UTP 2024 - 48 horas de código, pizza y Red Bull. Inscripciones abiertas hasta el viernes. Premio: S/5000',
        likes: 890,
        comentarios: 345,
        fecha: now.subtract(const Duration(hours: 1)),
        nombreUsuario: 'Carlos Rodríguez',
        nombreComunidad: 'Desarrollo Web UTP',
      ),
      Post(
        id: 18,
        usuarioId: 4,
        comunidadId: 8,
        contenido: '🎭 Audiciones para la obra de teatro de este semestre: "La casa de Bernarda Alba". Todos los niveles bienvenidos.',
        likes: 123,
        comentarios: 45,
        fecha: now.subtract(const Duration(hours: 3)),
        nombreUsuario: 'Ana Martínez',
        nombreComunidad: 'Música y Arte',
      ),
      Post(
        id: 19,
        usuarioId: 5,
        comunidadId: 2,
        contenido: '🧠 Importante: No descuiden su salud mental en época de exámenes. El CAPS está ofreciendo talleres de manejo del estrés.',
        likes: 445,
        comentarios: 123,
        fecha: now.subtract(const Duration(minutes: 30)),
        nombreUsuario: 'Pedro Sánchez',
        nombreComunidad: 'Medicina UTP - Grupo de Estudio',
      ),
      Post(
        id: 20,
        usuarioId: 6,
        comunidadId: 4,
        contenido: '🔥 Reto de la semana: Resolver 5 problemas de DP en Codeforces. Quien logre el rating más alto gana una polera del club.',
        likes: 67,
        comentarios: 89,
        fecha: now.subtract(const Duration(minutes: 15)),
        nombreUsuario: 'Laura Torres',
        nombreComunidad: 'Club de Programación Competitiva',
      ),
    ];
  }

  // Comentarios de prueba
  static List<Comment> getComments() {
    final now = DateTime.now();
    return [
      Comment(
        id: 1,
        publicacionId: 1,
        usuarioId: 2,
        contenido: '¡Felicitaciones! Yo también estoy aprendiendo Flutter. ¿Qué recurso usaste para aprender?',
        fecha: now.subtract(const Duration(hours: 1)),
      ),
      Comment(
        id: 2,
        publicacionId: 1,
        usuarioId: 3,
        contenido: 'Se ve genial! El diseño está muy limpio.',
        fecha: now.subtract(const Duration(minutes: 45)),
      ),
      Comment(
        id: 3,
        publicacionId: 2,
        usuarioId: 4,
        contenido: 'Gracias por compartir! Me salvaste para el examen de mañana.',
        fecha: now.subtract(const Duration(hours: 3)),
      ),
      Comment(
        id: 4,
        publicacionId: 2,
        usuarioId: 5,
        contenido: '¿Tienes más apuntes de Neurología? Me interesa mucho.',
        fecha: now.subtract(const Duration(hours: 2)),
      ),
      Comment(
        id: 5,
        publicacionId: 3,
        usuarioId: 1,
        contenido: 'Increíble toma! ¿Qué cámara usaste?',
        fecha: now.subtract(const Duration(hours: 6)),
      ),
      Comment(
        id: 6,
        publicacionId: 3,
        usuarioId: 6,
        contenido: 'El momento justo, hermosa composición.',
        fecha: now.subtract(const Duration(hours: 5)),
      ),
      Comment(
        id: 7,
        publicacionId: 6,
        usuarioId: 2,
        contenido: 'Vaya partidazo! La remontada fue épica.',
        fecha: now.subtract(const Duration(hours: 18)),
      ),
      Comment(
        id: 8,
        publicacionId: 9,
        usuarioId: 5,
        contenido: 'Flutter definitivamente. El hot reload y la experiencia de desarrollo son superiores.',
        fecha: now.subtract(const Duration(days: 2)),
      ),
      Comment(
        id: 9,
        publicacionId: 9,
        usuarioId: 3,
        contenido: 'Depende del caso. Para equipos grandes, React Native tiene más developers disponibles.',
        fecha: now.subtract(const Duration(days: 2, hours: 2)),
      ),
      Comment(
        id: 10,
        publicacionId: 10,
        usuarioId: 1,
        contenido: 'Ya postulé! Ojalá me den la oportunidad.',
        fecha: now.subtract(const Duration(days: 2)),
      ),
      Comment(
        id: 11,
        publicacionId: 13,
        usuarioId: 3,
        contenido: 'Yo juego de alero, me apunto!',
        fecha: now.subtract(const Duration(hours: 4)),
      ),
      Comment(
        id: 12,
        publicacionId: 13,
        usuarioId: 4,
        contenido: '¿Necesitan bases? Tengo experiencia en ligas juveniles.',
        fecha: now.subtract(const Duration(hours: 3)),
      ),
      Comment(
        id: 13,
        publicacionId: 16,
        usuarioId: 5,
        contenido: 'Hermosa composición! Me encanta cómo usaste la regla de los tercios.',
        fecha: now.subtract(const Duration(hours: 1)),
      ),
      Comment(
        id: 14,
        publicacionId: 17,
        usuarioId: 2,
        contenido: 'Voy a inscribir mi equipo! ¿Cuántos integrantes permiten?',
        fecha: now.subtract(const Duration(minutes: 30)),
      ),
      Comment(
        id: 15,
        publicacionId: 17,
        usuarioId: 6,
        contenido: 'Máximo 4 personas por equipo según las bases.',
        fecha: now.subtract(const Duration(minutes: 20)),
      ),
      Comment(
        id: 16,
        publicacionId: 19,
        usuarioId: 1,
        contenido: 'Gracias por recordarlo, justo estaba muy estresado con los exámenes.',
        fecha: now.subtract(const Duration(minutes: 15)),
      ),
      Comment(
        id: 17,
        publicacionId: 20,
        usuarioId: 3,
        contenido: 'Voy por esa polera! Ya resolví 3 problemas.',
        fecha: now.subtract(const Duration(minutes: 5)),
      ),
      Comment(
        id: 18,
        publicacionId: 5,
        usuarioId: 4,
        contenido: '¿Se necesita inscripción previa o es llegar y entrar?',
        fecha: now.subtract(const Duration(hours: 12)),
      ),
      Comment(
        id: 19,
        publicacionId: 7,
        usuarioId: 5,
        contenido: 'Tienes una voz increíble! Sigues así.',
        fecha: now.subtract(const Duration(days: 1)),
      ),
      Comment(
        id: 20,
        publicacionId: 11,
        usuarioId: 6,
        contenido: 'Me encanta esta serie fotográfica, sigue compartiendo!',
        fecha: now.subtract(const Duration(days: 3)),
      ),
    ];
  }

  // Notificaciones de prueba
  static List<NotificationModel> getNotifications() {
    final now = DateTime.now();
    return [
      NotificationModel(
        id: 1,
        usuarioId: 1,
        tipo: 'like',
        titulo: 'María García',
        mensaje: 'Le dio like a tu publicación',
        imagenUrl: 'https://i.pravatar.cc/150?u=2',
        fechaCreacion: now.subtract(const Duration(minutes: 5)),
        leida: false,
        referenciaId: 1,
      ),
      NotificationModel(
        id: 2,
        usuarioId: 1,
        tipo: 'comentario',
        titulo: 'Carlos Rodríguez',
        mensaje: 'Comentó: "Se ve genial!"',
        imagenUrl: 'https://i.pravatar.cc/150?u=3',
        fechaCreacion: now.subtract(const Duration(minutes: 30)),
        leida: false,
        referenciaId: 1,
      ),
      NotificationModel(
        id: 3,
        usuarioId: 1,
        tipo: 'seguir',
        titulo: 'Ana Martínez',
        mensaje: 'Comenzó a seguirte',
        imagenUrl: 'https://i.pravatar.cc/150?u=4',
        fechaCreacion: now.subtract(const Duration(hours: 2)),
        leida: true,
      ),
      NotificationModel(
        id: 4,
        usuarioId: 1,
        tipo: 'invitacion',
        titulo: 'Desarrollo Web UTP',
        mensaje: 'Te invitó a unirte a la comunidad',
        imagenUrl: 'https://picsum.photos/seed/web/100/100',
        fechaCreacion: now.subtract(const Duration(hours: 5)),
        leida: false,
        referenciaId: 1,
      ),
      NotificationModel(
        id: 5,
        usuarioId: 1,
        tipo: 'publicacion',
        titulo: 'Pedro Sánchez',
        mensaje: 'Publicó en Deportes UTP',
        imagenUrl: 'https://i.pravatar.cc/150?u=5',
        fechaCreacion: now.subtract(const Duration(hours: 8)),
        leida: true,
        referenciaId: 6,
      ),
      NotificationModel(
        id: 6,
        usuarioId: 1,
        tipo: 'like',
        titulo: 'Laura Torres',
        mensaje: 'Y 5 personas más dieron like',
        imagenUrl: 'https://i.pravatar.cc/150?u=6',
        fechaCreacion: now.subtract(const Duration(days: 1)),
        leida: true,
        referenciaId: 3,
      ),
      NotificationModel(
        id: 7,
        usuarioId: 1,
        tipo: 'mencion',
        titulo: 'Juan Pérez',
        mensaje: 'Te mencionó en un comentario',
        imagenUrl: 'https://i.pravatar.cc/150?u=1',
        fechaCreacion: now.subtract(const Duration(days: 1, hours: 6)),
        leida: false,
        referenciaId: 9,
      ),
      NotificationModel(
        id: 8,
        usuarioId: 1,
        tipo: 'sistema',
        titulo: 'UTP Comunidades',
        mensaje: 'Tu perfil ha sido verificado',
        imagenUrl: null,
        fechaCreacion: now.subtract(const Duration(days: 2)),
        leida: true,
      ),
    ];
  }

  // Mensajes de chat de prueba (para comunidades)
  static List<Map<String, dynamic>> getCommunityMessages() {
    final now = DateTime.now();
    return [
      {
        'id': 1,
        'comunidadId': 1,
        'usuarioId': 1,
        'mensaje': 'Hola a todos! Alguien sabe cuándo es la próxima reunión del club?',
        'fecha': now.subtract(const Duration(days: 2)),
      },
      {
        'id': 2,
        'comunidadId': 1,
        'usuarioId': 2,
        'mensaje': 'Creo que es el jueves a las 6pm en el lab 302',
        'fecha': now.subtract(const Duration(days: 2, hours: 1)),
      },
      {
        'id': 3,
        'comunidadId': 1,
        'usuarioId': 3,
        'mensaje': 'Confirmado, ahí nos vemos! Voy a llevar mi laptop para mostrar el proyecto.',
        'fecha': now.subtract(const Duration(days: 1, hours: 22)),
      },
      {
        'id': 4,
        'comunidadId': 1,
        'usuarioId': 1,
        'mensaje': 'Genial, yo también preparé algunos ejemplos de Flutter.',
        'fecha': now.subtract(const Duration(days: 1, hours: 20)),
      },
      {
        'id': 5,
        'comunidadId': 2,
        'usuarioId': 4,
        'mensaje': 'Alguien tiene los apuntes de la clase de hoy? Tuve que salir temprano.',
        'fecha': now.subtract(const Duration(hours: 4)),
      },
      {
        'id': 6,
        'comunidadId': 2,
        'usuarioId': 5,
        'mensaje': 'Yo los tengo, te los paso por WhatsApp',
        'fecha': now.subtract(const Duration(hours: 3)),
      },
      {
        'id': 7,
        'comunidadId': 3,
        'usuarioId': 2,
        'mensaje': 'Alguien quiere salir a tomar fotos este fin de semana?',
        'fecha': now.subtract(const Duration(hours: 6)),
      },
      {
        'id': 8,
        'comunidadId': 3,
        'usuarioId': 6,
        'mensaje': 'Yo me apunto! Pensaba ir al centro histórico.',
        'fecha': now.subtract(const Duration(hours: 5)),
      },
      {
        'id': 9,
        'comunidadId': 3,
        'usuarioId': 3,
        'mensaje': 'Cuente conmigo, llevo mi cámara réflex.',
        'fecha': now.subtract(const Duration(hours: 4)),
      },
      {
        'id': 10,
        'comunidadId': 4,
        'usuarioId': 1,
        'mensaje': 'Acabo de resolver el problema de la semana en Codeforces. Les comparto mi solución.',
        'fecha': now.subtract(const Duration(hours: 2)),
      },
    ];
  }
}
